[package]
name = "day7"
version = "0.1.0"
authors = ["Mathieu Letendre-Jauniaux <MathieuLJ@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "*"
clap = { version = "4", features = ["derive"] }
indoc = "*"
itertools = "*"
nom = "*"
nom-supreme = "*"
common = { path = "../common" }
